enum DialogType {
  BASIC,
  NOTIFICATION, //Demo
  BRANDS_LIST_DIALOGBOX,
  UPDATE_PRODUCT,
  GET_PRODUCT_BY_ID,
  ChANGE_PASSWORD,
  ADD_PRODUCT_QUANTITY,
  PRODUCT_DETAILS,
  PRODUCTS_FILTER,
  PRODUCTS_SORT,
  DELIVERY_DETAILS,
  DISCARD_PRODUCT,
  ADD_PRODUCT_TO_CART,
  ADD_ADDRESS,
  ORDER_LIST_FILTERS,
  DEMAND_APP_QR_CODE,
  SUPPLY_APP_QR_CODE,
  ORDER_PROCESS_CONFIRMATION
}
