// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqCe7RJUn60_VC1nOvFuJOneJskcIHoNM',
    appId: '1:6210683209:android:d4f0627511f33c5d389a98',
    messagingSenderId: '6210683209',
    projectId: 'geekscmsystem',
    storageBucket: 'geekscmsystem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHPsPbH4e02m-HOC2iHp_0wqfZQCZxqLQ',
    appId: '1:6210683209:ios:f321ee214c6a8cdd389a98',
    messagingSenderId: '6210683209',
    projectId: 'geekscmsystem',
    storageBucket: 'geekscmsystem.appspot.com',
    iosClientId: '6210683209-n0bs57qh4vn8cj6aumut8dj7fehsc93q.apps.googleusercontent.com',
    iosBundleId: 'com.geektecnotonic.scm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHPsPbH4e02m-HOC2iHp_0wqfZQCZxqLQ',
    appId: '1:6210683209:ios:f321ee214c6a8cdd389a98',
    messagingSenderId: '6210683209',
    projectId: 'geekscmsystem',
    storageBucket: 'geekscmsystem.appspot.com',
    iosClientId: '6210683209-n0bs57qh4vn8cj6aumut8dj7fehsc93q.apps.googleusercontent.com',
    iosBundleId: 'com.geektecnotonic.scm',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSzUdobLGj_-bOF1BQ9xcxB4Re6DHxrE0',
    appId: '1:6210683209:web:e0001a88eadb1320389a98',
    messagingSenderId: '6210683209',
    projectId: 'geekscmsystem',
    authDomain: 'geekscmsystem.firebaseapp.com',
    storageBucket: 'geekscmsystem.appspot.com',
    measurementId: 'G-W5LQ1VXNZ4',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }
}
